[package]
name = "test-husky"
version = "0.1.0"
authors = ["Ken OKADA <keno.ss57@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
