[package]
name = "test-husky"
version = "0.1.0"
authors = ["Ken OKADA <keno.ss57@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies.cargo-husky]
version = "1"
default-features = true
features = ["user-hooks"]
